### ISSUE TITLE
Pocket Casts Playback: 2023

### ISSUE THREAD

**Issue by leandroalonso** [Automattic/pocket-casts-ios#1142]
## Stories design

- [x] Intro Story #1145
- [x] Total episodes / shows #1150
- [x] Most listened show #1155
- [x] Top 5 shows #1157 
- [x] Top categories #1161 
- [x] Total time listening to podcasts #1163 
- [x] Longest episode #1164
- [x] Prologue #1166 

## Plus

- [x] Listening hours comparison story #1174
- [x] Completion rate story #1175 
- [x] Add a mechanism to skip "Plus stories" #1178
- [x] Plus Upsell story #1189
- [x] Plus purchase flow #1189
- [x] Add logic to sync 2022 data #1191

## Entry point

- [x] Update the modal entry point #1169
- [x] Update the Profile entry point #1169

## Tracks

- [x] Double check Tracks #1196
- [x] Add tracks for Plus #1196

## Refinements

- [x] Calculate top podcasts based on listening time AND number of episodes #1192
- [x] Gradient should be relative to the screen height and plus/normal gradient can be combined into one #1192
- [x] In small devices the font is too small #1192
- [x] Update the Pocket Casts watermark when exporting #1192
- [x] Fix the logo snapping issue on the IntroStory when the motion kicks in

## Animations

- [x] Add animation to the listened time story #1203
- [x] Add animation to the top five story to top 1 transition #1203
- [x] Add animation to the longest episode story #1203

## Additional

- [x] Update the share copies #1192
- [x] The old login flow is displayed, it should be replaced by the new one #1189
- [x] On the first story, add the numbers separately and add different parallax effects in each of them #1192
- [x] Prompt user to share when they take a screenshot #1193
- [x] Look at if we should show the YOY if 2022 is zero, [ref](https://github.com/Automattic/pocket-casts-ios/pull/1191#issuecomment-1801905103)
