### ISSUE TITLE
Project Issue: Refactor IAP Code

### ISSUE THREAD

**Issue by SergioEstevao** [Automattic/pocket-casts-ios#1373]
IAP code is in need of a refactor to address the following issues:

- Code spread out between the Constants file and the IAPHelper class
- No Unit Tests
- Use of strings and rawValue to identify products instead of proper use of enums
- Some IAPHelper methods are using a Objective-C naming convention 
- Some unused methods

```[tasklist]
### Tasks
- [x] Move IAP types out of Constants to separate file
- [x] Move IAP Helper to a separate Group
- [x] Add Unit tests for IAPHelper
- [x] Remove unused code
- [x] Rename method to use a Swift naming convention
- [x] Use enums to identify products
```
