### ISSUE TITLE
Deselecting Chapters

### ISSUE THREAD

**Issue by leandroalonso** [Automattic/pocket-casts-ios#1396]
Add the ability to deselect chapters and sync them between devices.

### Basics

- [x] Feature Flag #1397
- [x] Update the chapter UI to include way to choose which chapters to play #1399
- [x] While playing an episode and coming to the end of a chapter, skip to the next available chapter position #1426
- ~[ ] If the user scrubs to a playback position that is contained in a deselected chapter, playback should proceed as normal until reaching the end of that chapter~
- [x] Final design #1460 

### Paid Feature

- [x] Add the locked UI if the feature is not available #1449
- [x] Show the upsell when tapped #1449
- [x] Enable the feature for Patron under early access #1449
- [x] Then Plus for full access #1449

### Syncing

- [x] Send the selections to the server #1480
- [x] Apply incoming selections from the server #1480

### Watch

- [x] Skip deselected chapters on the watch when tapping the chapter next/previous buttons #1480

### Other

- [x] Add What’s New #1473
- [x] Add the feature to the plus features list #1467 
- [x] Tracks #1462

**Comment by rviljoen** [comment]
@leandroalonso Nice job. This is working very well 👌🏻
