### ISSUE TITLE
Settings Sync Project

### ISSUE THREAD

**Issue by bjtitus** [Automattic/pocket-casts-ios#1400]
Project Issue for syncing all user settings between devices.

Project Thread: pdeCcb-31c-p2

```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/1402
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/1404
- [x] Update local settings storage for Modified Date
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/1461
```

```[tasklist]
### Settings Screens
- [x] General Settings
- [x] Podcast settings
- [x] Notification settings
- [x] Appearances settings
- [x] Auto Archive settings
- [x] Auto Add to Up Next
- [x] Storage and Data Usage
- [x] Headphone Controls
- [x] Files
- [x] Podcasts ••• Menu
- [x] Playback Effects
- [x] Player Shelf
```

**Comment by BKrnk1337** [comment]
Sounds great. Having all settings synced between iPhone and Apple Watch would be nice. I have so many individual settings per podcast. Does this "project" include this aswell?
