### ISSUE TITLE
Downloading streaming episodes with AVExportSession

### ISSUE THREAD

**Issue by SergioEstevao** [Automattic/pocket-casts-ios#1795]
```[tasklist]
### Tasks
- [x] Implement downloading of audio of episode, using the same data/stream used by the player, #1787
- [x] Integrate exporting/downloading code with the Downloading system. #1792
- [ ] https://github.com/Automattic/pocket-casts-ios/pull/1819
```
