### ISSUE TITLE
Give Rating Project

### ISSUE THREAD

**Issue by danielebogo** [Automattic/pocket-casts-ios#1879]
```[tasklist]
### Phase 1 - UI
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/1880
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/1882
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/1881
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/1883
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/1891
```

```[tasklist]
### Phase 2 - Connect to API
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/1886
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/1884
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/1885
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/1907
```

```[tasklist]
### Issues
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/1890
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/1897
```

```[tasklist]
### Pre-release Tasks
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/1922
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/1965
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/2010
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/2033
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/2047
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/2089
```
