### ISSUE TITLE
Kids profile

### ISSUE THREAD

**Issue by danielebogo** [Automattic/pocket-casts-ios#1935]
```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/1936
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/1937
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/1938
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/1956
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/1940
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/1939
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/2001
```
