### ISSUE TITLE
Paywall Experiments

### ISSUE THREAD

**Issue by danielebogo** [Automattic/pocket-casts-ios#1986]
```[tasklist]
### Phase 1
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/1987
```
```[tasklist]
### Phase 2
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/2030
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/2032
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/2061
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/2031
```
```[tasklist]
### Phase 3
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/2213
- [x] Test Tracks events with all new variatons
```
