### ISSUE TITLE
Referrals - Phase 1

### ISSUE THREAD

**Issue by SergioEstevao** [Automattic/pocket-casts-ios#2083]
```[tasklist]
### Tasks
- [x] Send Pass: entry point on Profile View Controller - Gift Icon and Badge https://github.com/Automattic/pocket-casts-ios/pull/2082
- [x] Send Pass: hint that you have passes - https://github.com/Automattic/pocket-casts-ios/pull/2091
- [x] Send Pass : UI to send - https://github.com/Automattic/pocket-casts-ios/pull/2120
- [x] Send Pass: UI for gradient animation on passes - https://github.com/Automattic/pocket-casts-ios/pull/2143
- [x] Send Pass: API call to find referral code - https://github.com/Automattic/pocket-casts-ios/pull/2205
- [x] Send Pass: UI for user has no more passes https://github.com/Automattic/pocket-casts-ios/pull/2153
- [x] Send Pass: share UI https://github.com/Automattic/pocket-casts-ios/pull/2166
- [x] Claim pass: UI  for claim https://github.com/Automattic/pocket-casts-ios/pull/2158
- [x] Claim pass: UI for user already has subscription https://github.com/Automattic/pocket-casts-ios/pull/2178
- [x] Claim pass: Logic for parse referrals URLs and store referral IDs https://github.com/Automattic/pocket-casts-ios/pull/2178
- [x] Claim Pass: API calls to process referral received https://github.com/Automattic/pocket-casts-ios/pull/2223
- [x] Claim pass: Integrate signup/login flow https://github.com/Automattic/pocket-casts-ios/pull/2228
- [x] Claim Pass: Show new Account screen after referral purcahase when creating a new account https://github.com/Automattic/pocket-casts-ios/pull/2282
- [x] Claim Pass: Implement banner dismissal by long pressing banner cell - https://github.com/Automattic/pocket-casts-ios/pull/2268
- [x] Analytics implementation https://github.com/Automattic/pocket-casts-ios/pull/2231
- [x] Switch offer period to 2 months https://github.com/Automattic/pocket-casts-ios/pull/2162
- [x] Send Pass: Update to unlimited passes https://github.com/Automattic/pocket-casts-ios/pull/2164
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/2184
- [x] IAP: Implement promotion offer discount https://github.com/Automattic/pocket-casts-ios/pull/2274
- [x] Send Pass: Improve sharing items on Email / Messages to avoid duplication of URL https://github.com/Automattic/pocket-casts-ios/pull/2333
```

**Comment by SergioEstevao** [comment]
Version `7.76` has now entered code-freeze, so the milestone of this PR has been updated to `7.77`.

**Comment by danielebogo** [comment]
Version `7.77` has now entered code-freeze, so the milestone of this PR has been updated to `7.78`.
