### ISSUE TITLE
Search in Listening History 

### ISSUE THREAD

**Issue by danielebogo** [Automattic/pocket-casts-ios#2181]
```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/2191
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/2199
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/2207
```

**Comment by SergioEstevao** [comment]
Version `7.74` has now entered code-freeze, so the milestone of this PR has been updated to `7.75`.
