### ISSUE TITLE
Custom Playback Settings

### ISSUE THREAD

**Issue by danielebogo** [Automattic/pocket-casts-ios#2253]
```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/2254
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/2266
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/2283
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/2281
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/2297
```

**Comment by danielebogo** [comment]
Version `7.75` has now entered code-freeze, so the milestone of this PR has been updated to `7.76`.
