### ISSUE TITLE
Project: Auto Downloading Episodes

### ISSUE THREAD

**Issue by SergioEstevao** [Automattic/pocket-casts-ios#2284]
```[tasklist]
### Tasks
- [x] Implement Global Screen settings
- [x] Implement podcast settings
- [x] Implement download of episode when subscribing
- [x] Implement global disabling auto download
```

**Comment by SergioEstevao** [comment]
Close in favor of Github project: https://github.com/orgs/Automattic/projects/1177/views/1
