### ISSUE TITLE
Watch: migrate the Watch app to SwiftUI

### ISSUE THREAD

**Issue by pocketcasts** [Automattic/pocket-casts-ios#23]
## Phase 1 - Isolated screens
- [x] EffectsInterfaceController
- [x] MenuController (**Edit** This item is TBD see below on the comments)
- [x] FilesOrderInterfaceController
- [x] PodcastEpisodeOrderController
- [x] PodcastsOrderInterfaceController

## Phase 2 - Episode List Prep
- [x] Reference each other and should be merged together or account for the navigation
    - [x] EpisodeController
    - [x] PodcastEpisodeListController 

## Phase 3 - Episode Lists and Inter-dependencies
- [x] PodcastsInterfaceController
- [x] DownloadInterfaceController
- [x] FilterInterfaceController
- [x] FilesInterfaceController
- ~[ ] Reference each other and should be merged together or account for the navigation~
    - [x] UpNextInterfaceController
    - [x] NowPlayingInterfaceController

## Phase 4 - Remaining views (Should be done sequentially) 
- [x] FiltersInterfaceController - https://github.com/Automattic/pocket-casts-ios/pull/1524
- [x] InterfaceController
    - [x] handle state restoration 
- [x] SourceInterfaceController #1800

## Phase 5 - Review unknown elements
- [x] Static Notification Interface Controller Scene #1800
- [x] NotificationController (Empty view) #1800
- [x] Clean up any remaining WatchOS 7 migration warnings #1800
- [ ] Ensure `Screenshot Automation Watch` still runs

**Comment by SergioEstevao** [comment]
Should this project also include migrating the `.xcproj` file to have a single Watch OS project and also get rid of the Storyboards files and the startup cycle of the app?

It looks this was changed on XCode 14: https://stackoverflow.com/questions/52687924/ios-watchos-what-is-the-difference-between-watchkit-app-and-watchkit-app-exten
