### ISSUE TITLE
[Epic] HTML Podcast Descriptions

### ISSUE THREAD

**Issue by SergioEstevao** [Automattic/pocket-casts-ios#2479]
- [x] Fetch new HTML podcast description
- [x] Add database support for podcast description
- [x] Add UI support to formatting HTML podcast subscription

**Comment by SergioEstevao** [comment]
Version `7.79` has now entered code-freeze, so the milestone of this PR has been updated to `7.80`.

**Comment by danielebogo** [comment]
Version `7.80` has now entered code-freeze, so the milestone of this PR has been updated to `7.81`.

**Comment by SergioEstevao** [comment]
Version `7.81` has now entered code-freeze, so the milestone of this PR has been updated to `7.82`.

**Comment by pocketcasts** [comment]
Version `7.82` has now entered code-freeze, so the milestone of this PR has been updated to `7.83`.

**Comment by pocketcasts** [comment]
Version `7.83` has now entered code-freeze, so the milestone of this PR has been updated to `7.84`.
