### ISSUE TITLE
Feature Flag Removal

### ISSUE THREAD

**Issue by SergioEstevao** [Automattic/pocket-casts-ios#2509]
```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/2510
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/2511
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/2528
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/2531
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/2547
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/2559
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/2567
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/2570
- [ ] https://github.com/Automattic/pocket-casts-ios/issues/2579
```

**Comment by SergioEstevao** [comment]
Version `7.79` has now entered code-freeze, so the milestone of this PR has been updated to `7.80`.

**Comment by danielebogo** [comment]
Version `7.80` has now entered code-freeze, so the milestone of this PR has been updated to `7.81`.

**Comment by SergioEstevao** [comment]
Version `7.81` has now entered code-freeze, so the milestone of this PR has been updated to `7.82`.

**Comment by pocketcasts** [comment]
Version `7.82` has now entered code-freeze, so the milestone of this PR has been updated to `7.83`.

**Comment by pocketcasts** [comment]
Version `7.83` has now entered code-freeze, so the milestone of this PR has been updated to `7.84`.

**Comment by pocketcasts** [comment]
Version `7.84` has now entered code-freeze, so the milestone of this PR has been updated to `7.85`.

**Comment by pocketcasts** [comment]
Version `7.85` has now entered code-freeze, so the milestone of this PR has been updated to `7.86`.

**Comment by pocketcasts** [comment]
Version `7.86` has now entered code-freeze, so the milestone of this PR has been updated to `7.87`.

**Comment by pocketcasts** [comment]
Version `7.87` has now entered code-freeze, so the milestone of this PR has been updated to `7.88`.

**Comment by pocketcasts** [comment]
Version `7.88` has now entered code-freeze, so the milestone of this PR has been updated to `7.89`.

**Comment by pocketcasts** [comment]
Version `7.89` has now entered code-freeze, so the milestone of this PR has been updated to `7.90`.

**Comment by pocketcasts** [comment]
Version `7.90` has now entered code-freeze, so the milestone of this PR has been updated to `7.91`.

**Comment by pocketcasts** [comment]
Version `7.91` has now entered code-freeze, so the milestone of this PR has been updated to `7.92`.

**Comment by pocketcasts** [comment]
Version `7.92` has now entered code-freeze, so the milestone of this PR has been updated to `7.93`.

**Comment by pocketcasts** [comment]
Version `7.93` has now entered code-freeze, so the milestone of this PR has been updated to `7.94`.

**Comment by pocketcasts** [comment]
Version `7.94` has now entered code-freeze, so the milestone of this PR has been updated to `7.95`.

**Comment by pocketcasts** [comment]
Version `7.95` has now entered code-freeze, so the milestone of this PR has been updated to `7.96`.

**Comment by pocketcasts** [comment]
Version `7.96` has now entered code-freeze, so the milestone of this PR has been updated to `7.97`.

**Comment by pocketcasts** [comment]
Version `7.97` has now entered code-freeze, so the milestone of this PR has been updated to `7.98`.

**Comment by pocketcasts** [comment]
Version `7.98` has now entered code-freeze, so the milestone of this PR has been updated to `7.99`.

**Comment by pocketcasts** [comment]
Version `7.99` has now entered code-freeze, so the milestone of this PR has been updated to `7.100`.

**Comment by pocketcasts** [comment]
Version `7.100` has now entered code-freeze, so the milestone of this PR has been updated to `7.101`.

**Comment by pocketcasts** [comment]
Version `7.101` has now entered code-freeze, so the milestone of this PR has been updated to `7.102`.
