### ISSUE TITLE
Migrate Crash reporting from Crashlytics to Sentry

### ISSUE THREAD

**Issue by chipsnyder** [Automattic/pocket-casts-ios#341]
### Overview
On Android, we recently made the switch from Crashlytics to Sentry. In an effort to keep the tooling consistent within the product and within A8C the iOS team decided to scope out the work to make the same move for iOS.

In my experience, having two crash logging libraries active at the same time can be a recipe for trouble, so I’m recommending that we do a clean cut from Crashlytics to Sentry.

Like Crashlytics, Sentry has [limited symbolication support and no crash handling](https://docs.sentry.io/platforms/apple/guides/watchos/) for WatchOS. So this project won’t do anything for our watch app.

### Tasks
- [x] Prepare a Sentry project for the Pocket Casts iOS app
- ~[ ] Create a Debug Developer-focused screen with a force crash button for testing.~
- [x] Remove Crashlytics
- [x] Integrate Sentry from https://github.com/Automattic/Automattic-Tracks-iOS using the [CrashLogging](https://github.com/Automattic/Automattic-Tracks-iOS/blob/f10e463b59358cc8391746247e511cdcad6b9e92/Sources/Remote%20Logging/Crash%20Logging/CrashLogging.swift) wrapper.
    - This should consider Opt-Out
    - Add necessary credential items 
- [x] Update the release scripts to upload the dsyms to sentry
    - We should be able to use the [upload_symbols_to_sentry](http://docs.fastlane.tools/actions/upload_symbols_to_sentry/#upload_symbols_to_sentry) action and replace our make command ([1](https://github.com/Automattic/pocket-casts-ios/blob/7786534abfbaf48c07d6a7c3d7c1be37deac7a2d/fastlane/Fastfile#L148), [2](https://github.com/Automattic/pocket-casts-ios/blob/7786534abfbaf48c07d6a7c3d7c1be37deac7a2d/fastlane/Fastfile#L415))

**Comment by chipsnyder** [comment]
> Create a Debug Developer-focused screen with a force crash button for testing.

I dropped this requirement as it wasn't helpful in testing because Crashyltics and Sentry both require configuration changes to enable debug crashes. It's more efficient to test by inserting a `fatalError("Test Crash")` command where desired and running a release build.
