### ISSUE TITLE
Project: End of Year

### ISSUE THREAD

**Issue by leandroalonso** [Automattic/pocket-casts-ios#376]
## Description

Show end of year stats.

### Initial work

- [x] Add modal structure #377
- [x] Add stories structure #383
- [x] Add stories data source #389
- [x] Add profile card structure and badge #393

### Presenting and sharing Stories

- [x] Generate a story with dummy data #397
- [x] Generate an image based on the story shown #404
- [x] Share the generated image through a share sheet #404

### Stories data

- [x] Show total listening time in 2022 #411
- [x] Show number of different categories they’ve listened to #413
- [x] Show top 5 categories and how many podcasts in each of these they’ve listened to #413
- [x] Show total number of podcasts and episodes they’ve listened to. #414
- [x] Show number 1 podcast for 2022 #415
- [x] Show top 5 podcasts of the year #415
- [x] Show longest episode they listened to in 2022 #416
- [x] Show the first and last story (with the option to replay) #420
- [x] Refactor the data source to remove the queries to another place #428
- [x] Check eligibility and if the user has the whole 2022 Listening History, if not, grab their 2022 listening history from the server. #433

### Tracks

- [x] Add tracks #476

### Design

- [x] Finish the modal design and profile card design #441
- [x] Intro story #448 
- [x] Listening time story #452
- [x] Listened categories story #453 
- [x] Top categories story #468 
- [x] Listened podcasts story #454 
- [x] Top 1 podcast story #455 
- [x] Top 5 podcasts story #462 
- [x] Longest episode story #463 
- [x] Epilogue story #467 
- [x] Download colors before presenting podcasts and optimistically download podcasts covers #471
- [ ] Refactor views to reduce code duplication

### Misc

- [x] Implement the flow for logged out users and add a remote feature flag to toggle this behavior #474
- [x] Sharing: text and links #478
- [x] Test on iOS 14/15/16 and iPadOS 14/15/16 #495 

## Listening History Sync

- [x] Sync Listening History #483

## Nice to have

- [ ] Instead of using bottom sheet on iPad, present it as "a card"
- [ ] Add default colors to stories for when the colors don't load

**Comment by leandroalonso** [comment]
### Comments from reviews:

In #452

- [x] Make height/position dynamic
- [x] Display a placeholder while loading podcasts
- [x] Rename `randomPodcasts`

In #454

- [x] When there aren't many podcasts available it looks weird

All addressed in: https://github.com/Automattic/pocket-casts-ios/pull/489
