### ISSUE TITLE
Project: SSO

### ISSUE THREAD

**Issue by chipsnyder** [Automattic/pocket-casts-ios#381]
This issue is to help track the work to be done to enable Social Sign In

- [x] Google Sign In #649 
- [x] Token refresh mechanism #650 
- [x] Sign In With Apple #652 
- [x] Apple Watch #656
- [x] Sonos #667
- [x] Events #679 
- [x] Hide password reset and email change #672

## Additional

- [x] The "You've been logged out" triggers the previous login flow #674 
- [x] Remove SIWA authentication revoked (we should not log out the user) - Done as part of #656
- [ ] Memory leak when the onboarding flow dismisses automatically (without user interaction)

**Comment by emilylaguna** [comment]
Closing this as the project has been launched.
