### ISSUE TITLE
Search Improvements

### ISSUE THREAD

**Issue by leandroalonso** [Automattic/pocket-casts-ios#709]
### Search History

- A list of recent searches will be displayed now when the user focus the search input box. 
- Whenever a user selects an item in a search results list, the selected item will be saved in the search history, and displayed in the list described in this task (p1665038946092499/1664975388.327359-slack-C03JCLLR9C3).

#### Tasks

- [x] Create the view #732
- [x] Save search terms and tapped podcasts #770
- [x] Populate the view with saved terms/podcasts/episodes #770
- [x] Open search when term is tapped / Open podcast/episode when tapped #770
- [x] Add Analytics #774

### Inline search results

The search results will be divided in two areas: podcasts and episodes. Each area will display a "Show all" link that will carry the user to the podcasts/episodes search result screen.

#### Tasks

- [x] Show podcasts and episode search result from the new APIs #766
- [x] When tapping a podcast/episode show it #769
- [x] Show all podcasts on a new screen #771 
- [x] Make sure both Discover and Podcasts search work as intended #772
- [x] Show local podcasts #773 
- [x] Add Analytics #774
- [x] UI Improvements #778 

#### Issues

- [x] When adding a URL, return the podcast #780
- [x] Folders do not appear on the list results correctly #780
- [x] On the list result, there's no loading indicator #780
- [x] The history is out of sync between screens #780
- [x] When swiping in the carousel after a local search, it gets reset #780
- [x] The History seems to be saved as the user types #795
- [x] From Emily: "I have a folder in my history but it's been deleted but still appears and tapping it doesn't do anything" #795

**Comment by rviljoen** [comment]
Some good suggestions here https://github.com/Automattic/pocket-casts-ios/discussions/731

**Comment by CameronMilliken** [comment]
I see several search improvements were merged. Does anyone know if any of them would help this user?

> Can’t search anything include Podcast station by Traditional Chinese input.
Like keyword "台東漫波電台"
Can’t find anything on Pocket Cast
but the keyword “台東慢波電台 taitung mambo radio” can find the right podcast.
The search is not friendly for Chinese user.
![image](https://user-images.githubusercontent.com/36011531/223216119-bb555a99-05ac-4012-a68f-4109b0a63c0d.jpg)
![image (1)](https://user-images.githubusercontent.com/36011531/223216278-da01bb16-0395-493f-9c8a-589b8f4c1e98.jpg)

**Comment by ghost** [comment]
Looking really nice so far thanks @leandroalonso just noting a few things I've noticed so far while reviewing. 
<img width="625" alt="Screenshot 2023-04-04 at 8 10 49 pm" src="https://user-images.githubusercontent.com/74938219/229760791-2b39bdf8-bf7b-4606-832f-9de4143e700c.png">

**Recent Searches**
- it looks like we're displaying the wrong search icon here. Could we please [update to this one](https://www.figma.com/file/fs6qvDgcorsbCMUNyhGpd3uI/%F0%9F%9B%A0-Pocket-Casts-Design-System?node-id=2%3A73&t=Bdzf16Nfb26yhIh2-1)
- The shadows look a bit off on the artwork. I'm not sure if you have styles named something similar but I have the larger artwork set to 'Elevation' and the smaller ones set to 'Elevation Low'

**Results**
<img width="851" alt="Screenshot 2023-04-04 at 8 18 36 pm" src="https://user-images.githubusercontent.com/74938219/229762254-edbcb658-48c2-4098-bec1-fafc86cb961c.png">

- On the results page it doesn't look like the headings and artwork are properly aligned to the left.
- The shadows look a bit off here too can we please take a look at these as well?
- The artwork used in the episode list looks a bit smaller than it should be here. This might, however, be an inconsistency between what's shown in the design components and what's already in the app so this isn't a blocker. For reference though, I used the same size as what's in the episode lists and downloads list page so if we could just match what we use there that would be great, thanks.
- There's a scroll bar showing when scrolling the top podcasts carousel and it doesn't seem to have the same easing/movement as the carousels on the Discover page. Could we please try to match that behavior here too?

**Comment by leandroalonso** [comment]
@adamzelinski 

I addressed the issues here: https://github.com/Automattic/pocket-casts-ios/pull/805

As soon as it gets merged I'll release a new beta version and you can use it to test on your device, in the meantime please check the video.

**Recent Searches**

Addressed both issues. I have a question though: we have different icons on the tab bar and the search itself. Shall we be consistent with the icons or it doesn't make much difference?

**Results**

> On the results page it doesn't look like the headings and artwork are properly aligned to the left.

I reduced the padding. FYI: we have parts in the app in which this padding is bigger (Discover) and others that are small (Download list). Maybe when changing those areas in the future we might want to have some consistency between them.

> The shadows look a bit off here too can we please take a look at these as well?

Done.

> The artwork used in the episode list looks a bit smaller than it should be here. This might, however, be an inconsistency between what's shown in the design components and what's already in the app so this isn't a blocker. For reference though, I used the same size as what's in the episode lists and downloads list page so if we could just match what we use there that would be great, thanks.

I used Discover as a reference, that's why it was small. Changed to be bigger.

> There's a scroll bar showing when scrolling the top podcasts carousel and it doesn't seem to have the same easing/movement as the carousels on the Discover page. Could we please try to match that behavior here too?

So, there's a long answer to that. And one that is frustrating. 😬 SwiftUI doesn't have a component capable of doing that. The new search was entirely made using SwiftUI (not UIKit) and the part that we had more issues with was the carousel. We tried many different ways and approaches but none of them worked.

After talking to @ashiagr she shared with us that Android doesn't have a carousel, instead, it's horizontal scrolling. We did the same on iOS and that fixed all the layout issues we were experiencing.

I know this is frustrating and @emilylaguna and I tried to come up with a solution for that, but until SwiftUI adds better support to pages that's the best we can achieve on time.

Ps.: it might be that is simple to just reuse the component we already have. But... it's not. That was something that I also tried without success.
